
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 7;
  public static final int DIVIDE = 9;
  public static final int INTEGER = 3;
  public static final int SEMI = 10;
  public static final int EOF = 0;
  public static final int PLUS = 6;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int RPAREN = 5;
  public static final int TIMES = 8;
  public static final int LPAREN = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INTEGER",
  "LPAREN",
  "RPAREN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "SEMI"
  };
}

