
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 15;
  public static final int FDEF = 32;
  public static final int FLOAT_NUMBER = 9;
  public static final int ELSE = 23;
  public static final int PLUS = 13;
  public static final int RPAREN = 12;
  public static final int THEN = 22;
  public static final int LCURL = 28;
  public static final int WHILE = 24;
  public static final int SEMI = 17;
  public static final int RETURN = 31;
  public static final int FI = 21;
  public static final int FLOAT_TYPE = 6;
  public static final int IF = 20;
  public static final int COLON = 18;
  public static final int LPAREN = 11;
  public static final int ID = 2;
  public static final int OD = 26;
  public static final int DO = 25;
  public static final int COMMA = 30;
  public static final int RATIONAL_NUMBER = 10;
  public static final int INTEGER_TYPE = 4;
  public static final int EOF = 0;
  public static final int DIVIDE = 16;
  public static final int MAIN = 27;
  public static final int BOOLEAN_TYPE = 3;
  public static final int RATIONAL_TYPE = 5;
  public static final int MINUS = 14;
  public static final int error = 1;
  public static final int ASSIGN = 19;
  public static final int INTEGER_NUMBER = 8;
  public static final int RCURL = 29;
  public static final int BOOLEAN_VALUE = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "BOOLEAN_TYPE",
  "INTEGER_TYPE",
  "RATIONAL_TYPE",
  "FLOAT_TYPE",
  "BOOLEAN_VALUE",
  "INTEGER_NUMBER",
  "FLOAT_NUMBER",
  "RATIONAL_NUMBER",
  "LPAREN",
  "RPAREN",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "SEMI",
  "COLON",
  "ASSIGN",
  "IF",
  "FI",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "OD",
  "MAIN",
  "LCURL",
  "RCURL",
  "COMMA",
  "RETURN",
  "FDEF"
  };
}

